security:
    password_hashers:
        App\Entity\Users: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Users
                property: email

    firewalls:
        # 🔐 LOGIN (JWT)
        login:
            pattern: ^/api/login$
            stateless: true
            user_checker: App\Security\UserChecker
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
                success_handler: App\Security\JWTAuthenticationSuccessHandler
                failure_handler: App\Security\AuthenticationFailureHandler

        # 🔐 API protégée par JWT
        api:
            pattern: ^/api
            stateless: true
            user_checker: App\Security\UserChecker
            jwt: ~

        # 🔓 DEV
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # 🔓 MAIN
        main:
            lazy: true
            provider: app_user_provider

    access_control:
        - { path: ^/api/register, roles: PUBLIC_ACCESS }
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/forgot-password, roles: PUBLIC_ACCESS }
        - { path: ^/api/reset-password, roles: PUBLIC_ACCESS }
        - { path: ^/api/banned-appeal, roles: PUBLIC_ACCESS }
        - { path: ^/api/anouncements$, roles: PUBLIC_ACCESS }
        - { path: ^/api/anouncement/\d+$, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }